[workspace]
members = [
    "crystal-packing",
    "crystal-packing-cli",
    "crystal-packing-wasm",
]

[profile.release]
lto = true
panic =  "abort"
opt-level = 's'
codegen-units = 1

# [package.metadata.wasm-pack.profile.release]
# wasm-opt = ['-Os']
