[package]
name = "packing"
version = "0.1.0"
authors = ["Malcolm Ramsay <malramsay64@gmail.com>"]
edition = "2018"

[dependencies]
nalgebra = "0.16"
rand = "0.6"
approx = "0.3"
log = "0.4.0"
env_logger = "0.6.0"

[dev-dependencies]
criterion = "0.2"

[[bench]]
name = "intersection"
harness = false
