on: [push, pull_request]

name: Linters

jobs:
  rustfmt:
    name: Formatting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2.3.3
        with:
          submodules: true

      - name: Install latest nightly toolchain with rustfmt available
        uses: actions-rs/toolchain@v1
        with:
            toolchain: stable
            override: true

      - name: Install rustfmt component
        run: rustup component add rustfmt

      - name: Run cargo fmt
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check

  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2.3.3
        with:
          submodules: true

      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Run cargo check
        uses: actions-rs/cargo@v1
        with:
          command: check

  clippy:
    name: Clippy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2.3.3
        with:
          submodules: true

      - name: Install latest stable toolchain with clippy available
        uses: actions-rs/toolchain@v1
        with:
            toolchain: stable
            compoents: clippy
            override: true

      - name: Run cargo clippy
        uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --all-features -- -D warnings
